// Liste des pays — séparée pour garder RegisterPage lisible
const getCountryFlag = (code: string) => {
  if (code === 'INT') return '🌐';

  return code
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
};

const COUNTRIES = [
  { code: 'INT', name: 'International' },
  { code: 'FR', name: 'France' },
  { code: 'BE', name: 'Belgique' },
  { code: 'CH', name: 'Suisse' },
  { code: 'CA', name: 'Canada' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MC', name: 'Monaco' },
  { code: 'AD', name: 'Andorre' },
  { code: 'AE', name: 'Émirats Arabes Unis' },
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AG', name: 'Antigua-et-Barbuda' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'AL', name: 'Albanie' },
  { code: 'AM', name: 'Arménie' },
  { code: 'AO', name: 'Angola' },
  { code: 'AR', name: 'Argentine' },
  { code: 'AS', name: 'Samoa Américaines' },
  { code: 'AT', name: 'Autriche' },
  { code: 'AU', name: 'Australie' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AX', name: 'Îles Åland' },
  { code: 'AZ', name: 'Azerbaïdjan' },
  { code: 'BA', name: 'Bosnie-Herzégovine' },
  { code: 'BB', name: 'Barbade' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BG', name: 'Bulgarie' },
  { code: 'BH', name: 'Bahreïn' },
  { code: 'BI', name: 'Burundi' },
  { code: 'BJ', name: 'Bénin' },
  { code: 'BL', name: 'Saint-Barthélemy' },
  { code: 'BM', name: 'Bermudes' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BO', name: 'Bolivie' },
  { code: 'BQ', name: 'Pays-Bas Caribéens' },
  { code: 'BR', name: 'Brésil' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BT', name: 'Bhoutan' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BY', name: 'Biélorussie' },
  { code: 'BZ', name: 'Belize' },
  { code: 'CC', name: 'Îles Cocos' },
  { code: 'CD', name: 'République Démocratique du Congo' },
  { code: 'CF', name: 'République Centrafricaine' },
  { code: 'CG', name: 'République du Congo' },
  { code: 'CI', name: "Côte d'Ivoire" },
  { code: 'CK', name: 'Îles Cook' },
  { code: 'CL', name: 'Chili' },
  { code: 'CM', name: 'Cameroun' },
  { code: 'CN', name: 'Chine' },
  { code: 'CO', name: 'Colombie' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CV', name: 'Cap-Vert' },
  { code: 'CW', name: 'Curaçao' },
  { code: 'CX', name: 'Île Christmas' },
  { code: 'CY', name: 'Chypre' },
  { code: 'CZ', name: 'République Tchèque' },
  { code: 'DE', name: 'Allemagne' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DK', name: 'Danemark' },
  { code: 'DM', name: 'Dominique' },
  { code: 'DO', name: 'République Dominicaine' },
  { code: 'DZ', name: 'Algérie' },
  { code: 'EC', name: 'Équateur' },
  { code: 'EE', name: 'Estonie' },
  { code: 'EG', name: 'Égypte' },
  { code: 'EH', name: 'Sahara Occidental' },
  { code: 'ER', name: 'Érythrée' },
  { code: 'ES', name: 'Espagne' },
  { code: 'ET', name: 'Éthiopie' },
  { code: 'FI', name: 'Finlande' },
  { code: 'FJ', name: 'Fidji' },
  { code: 'FK', name: 'Îles Malouines' },
  { code: 'FM', name: 'Micronésie' },
  { code: 'FO', name: 'Îles Féroé' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GB', name: 'Royaume-Uni' },
  { code: 'GD', name: 'Grenade' },
  { code: 'GE', name: 'Géorgie' },
  { code: 'GF', name: 'Guyane Française' },
  { code: 'GG', name: 'Guernesey' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GL', name: 'Groenland' },
  { code: 'GM', name: 'Gambie' },
  { code: 'GN', name: 'Guinée' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'GQ', name: 'Guinée Équatoriale' },
  { code: 'GR', name: 'Grèce' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GU', name: 'Guam' },
  { code: 'GW', name: 'Guinée-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HR', name: 'Croatie' },
  { code: 'HT', name: 'Haïti' },
  { code: 'HU', name: 'Hongrie' },
  { code: 'ID', name: 'Indonésie' },
  { code: 'IE', name: 'Irlande' },
  { code: 'IL', name: 'Israël' },
  { code: 'IM', name: 'Île de Man' },
  { code: 'IN', name: 'Inde' },
  { code: 'IO', name: "Territoire Britannique de l'Océan Indien" },
  { code: 'IQ', name: 'Irak' },
  { code: 'IR', name: 'Iran' },
  { code: 'IS', name: 'Islande' },
  { code: 'IT', name: 'Italie' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JM', name: 'Jamaïque' },
  { code: 'JO', name: 'Jordanie' },
  { code: 'JP', name: 'Japon' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KG', name: 'Kirghizistan' },
  { code: 'KH', name: 'Cambodge' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KM', name: 'Comores' },
  { code: 'KN', name: 'Saint-Kitts-et-Nevis' },
  { code: 'KP', name: 'Corée du Nord' },
  { code: 'KR', name: 'Corée du Sud' },
  { code: 'KW', name: 'Koweït' },
  { code: 'KY', name: 'Îles Caïmans' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LB', name: 'Liban' },
  { code: 'LC', name: 'Sainte-Lucie' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'LR', name: 'Libéria' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LT', name: 'Lituanie' },
  { code: 'LV', name: 'Lettonie' },
  { code: 'LY', name: 'Libye' },
  { code: 'MA', name: 'Maroc' },
  { code: 'MD', name: 'Moldavie' },
  { code: 'ME', name: 'Monténégro' },
  { code: 'MF', name: 'Saint-Martin' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MH', name: 'Îles Marshall' },
  { code: 'MK', name: 'Macédoine du Nord' },
  { code: 'ML', name: 'Mali' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'MN', name: 'Mongolie' },
  { code: 'MO', name: 'Macao' },
  { code: 'MP', name: 'Îles Mariannes du Nord' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MR', name: 'Mauritanie' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MT', name: 'Malte' },
  { code: 'MU', name: 'Maurice' },
  { code: 'MV', name: 'Maldives' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MX', name: 'Mexique' },
  { code: 'MY', name: 'Malaisie' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'NA', name: 'Namibie' },
  { code: 'NC', name: 'Nouvelle-Calédonie' },
  { code: 'NE', name: 'Niger' },
  { code: 'NF', name: 'Île Norfolk' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NL', name: 'Pays-Bas' },
  { code: 'NO', name: 'Norvège' },
  { code: 'NP', name: 'Népal' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NU', name: 'Niue' },
  { code: 'NZ', name: 'Nouvelle-Zélande' },
  { code: 'OM', name: 'Oman' },
  { code: 'PA', name: 'Panama' },
  { code: 'PE', name: 'Pérou' },
  { code: 'PF', name: 'Polynésie Française' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PL', name: 'Pologne' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon' },
  { code: 'PN', name: 'Îles Pitcairn' },
  { code: 'PR', name: 'Porto Rico' },
  { code: 'PS', name: 'Palestine' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PW', name: 'Palaos' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RE', name: 'La Réunion' },
  { code: 'RO', name: 'Roumanie' },
  { code: 'RS', name: 'Serbie' },
  { code: 'RU', name: 'Russie' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'SA', name: 'Arabie Saoudite' },
  { code: 'SB', name: 'Îles Salomon' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SD', name: 'Soudan' },
  { code: 'SE', name: 'Suède' },
  { code: 'SG', name: 'Singapour' },
  { code: 'SH', name: 'Sainte-Hélène' },
  { code: 'SI', name: 'Slovénie' },
  { code: 'SJ', name: 'Svalbard et Jan Mayen' },
  { code: 'SK', name: 'Slovaquie' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SM', name: 'Saint-Marin' },
  { code: 'SN', name: 'Sénégal' },
  { code: 'SO', name: 'Somalie' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SS', name: 'Soudan du Sud' },
  { code: 'ST', name: 'Sao Tomé-et-Principe' },
  { code: 'SV', name: 'Salvador' },
  { code: 'SX', name: 'Saint-Martin (Pays-Bas)' },
  { code: 'SY', name: 'Syrie' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'TC', name: 'Îles Turques-et-Caïques' },
  { code: 'TD', name: 'Tchad' },
  { code: 'TF', name: 'Terres Australes Françaises' },
  { code: 'TG', name: 'Togo' },
  { code: 'TH', name: 'Thaïlande' },
  { code: 'TJ', name: 'Tadjikistan' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TL', name: 'Timor Oriental' },
  { code: 'TM', name: 'Turkménistan' },
  { code: 'TN', name: 'Tunisie' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TR', name: 'Turquie' },
  { code: 'TT', name: 'Trinité-et-Tobago' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'TW', name: 'Taïwan' },
  { code: 'TZ', name: 'Tanzanie' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'UG', name: 'Ouganda' },
  { code: 'US', name: 'États-Unis' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Ouzbékistan' },
  { code: 'VA', name: 'Vatican' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VG', name: 'Îles Vierges Britanniques' },
  { code: 'VI', name: 'Îles Vierges Américaines' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'WF', name: 'Wallis-et-Futuna' },
  { code: 'WS', name: 'Samoa' },
  { code: 'YE', name: 'Yémen' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'ZA', name: 'Afrique du Sud' },
  { code: 'ZM', name: 'Zambie' },
  { code: 'ZW', name: 'Zimbabwe' },
];

export const COUNTRY_OPTIONS = COUNTRIES.map((country) => ({
  ...country,
  flag: getCountryFlag(country.code),
}));
